<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="168063" started-at="2018-08-09T07:23:18Z" finished-at="2018-08-09T07:26:06Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="168063" started-at="2018-08-09T07:23:18Z" finished-at="2018-08-09T07:26:06Z">
      <class name="org.sunbird.testscripts.Announcement_TC06">
        <test-method status="PASS" signature="openApplication()[pri:0, instance:org.sunbird.testscripts.Announcement_TC06@26653222]" name="openApplication" is-config="true" duration-ms="13722" started-at="2018-08-09T00:23:18Z" finished-at="2018-08-09T00:23:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method status="FAIL" signature="resendAndVerifyAsReviewerAnnouncement_TC06()[pri:0, instance:org.sunbird.testscripts.Announcement_TC06@26653222]" name="resendAndVerifyAsReviewerAnnouncement_TC06" duration-ms="153884" started-at="2018-08-09T00:23:31Z" finished-at="2018-08-09T00:26:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<AnnouncementA> but was:<AnnouncementAA0017>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<AnnouncementA> but was:<AnnouncementAA0017>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at org.sunbird.testscripts.Announcement_TC06.resendAndVerifyAsReviewerAnnouncement_TC06(Announcement_TC06.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resendAndVerifyAsReviewerAnnouncement_TC06 -->
        <test-method status="PASS" signature="closeApplication()[pri:0, instance:org.sunbird.testscripts.Announcement_TC06@26653222]" name="closeApplication" is-config="true" duration-ms="328" started-at="2018-08-09T00:26:05Z" finished-at="2018-08-09T00:26:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
      </class> <!-- org.sunbird.testscripts.Announcement_TC06 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
